[project]
name = "4-week-program"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "pydantic-ai>=0.2.4",
    "pydantic-ai-slim[anthropic,gemini,mistral,ollama,openai]>=0.2.4",
    "pytest>=8.3.5",
    "streamlit>=1.45.1",
]
